# docker-compose 의 버전 정의
version: "3"
# 실행하려는 컨테이너들을 정의
services:
  # ---------------------------------------------------- 개발용
  # 컨테이너 이름
  next:
    container_name: "next"
    restart: "always"
    build:
      context: ./next
      # 현 디렉토리에 있는 Dockerfile.dev 사용
      dockerfile: Dockerfile.dev
    # 해당 컨테이너의 포트 매핑
    ports:
      - 3000:3000
    # 볼륨 설정
    volumes:
      # hot reload를 위해 mount
      - "./next:/usr/src/next"
      - "/usr/src/next/node_modules"
      - "/usr/src/next/.next"
    environment:
      NEXT_PUBLIC_API_URL: https://api.example.com

  # # ----------------------------------------------------- 테스트용
  # tests:
  #   container_name: "tests"
  #   restart: "always"
  #   build:
  #     context: ./next
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - "./next:/usr/src/next"
  #     - "/usr/src/next/node_modules"
  #     - "/usr/src/next/.next"
  #   command: ["npm", "run", "test"]

  # # ----------------------------------------------------- 배포용
  # next-prod:
  #   container_name: "next-prod"
  #   restart: "always"
  #   build:
  #     context: ./next
  #     # 현 디렉토리에 있는 Dockerfile.dev 사용
  #     dockerfile: Dockerfile.prod
  #   # 해당 컨테이너의 포트 매핑
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NEXT_PUBLIC_API_URL: https://api.example.com

  # nginx:
  #   image: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./next/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - next-prod
