# docker-compose 의 버전 정의
version: "3"
# 실행하려는 컨테이너들을 정의
services:
  # ---------------------------------------------------- nginx 공통
  nginx:
    restart: "always"
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nextjs

  # ---------------------------------------------------- dev
  # 컨테이너 이름
  nextjs:
    restart: "always"
    build:
      context: ./next
      # 현 디렉토리에 있는 Dockerfile.dev 사용
      dockerfile: Dockerfile.dev
    # 볼륨 설정
    volumes:
      # hot reload를 위해 mount
      - "./next:/usr/src/next"
      - "/usr/src/next/node_modules"
      - "/usr/src/next/.next"
    environment:
      NEXT_PUBLIC_API_URL: https://api.example.com

  # # ----------------------------------------------------- production
  # nextjs:
  #   restart: "always"
  #   build:
  #     context: ./next
  #     dockerfile: Dockerfile.prod
  #   volumes:
  #     # hot reload를 위해 mount
  #     - "./next:/usr/src/next"
  #     - "/usr/src/next/node_modules"
  #     - "/usr/src/next/.next"
  #   environment:
  #     NEXT_PUBLIC_API_URL: https://api.example.com

  # # ----------------------------------------------------- test
  # tests:
  #   container_name: "tests"
  #   restart: "always"
  #   build:
  #     context: ./next
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - "./next:/usr/src/next"
  #     - "/usr/src/next/node_modules"
  #     - "/usr/src/next/.next"
  #   command: ["npm", "run", "test"]
